/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Event */
        Event: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Address */
            address?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Starts At */
            starts_at: string;
            /** Ends At */
            ends_at?: string | null;
            /** Source */
            source?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Interest Tags
             * @default []
             */
            interest_tags: string[];
            /**
             * Vibe Tags
             * @default []
             */
            vibe_tags: string[];
            /**
             * Best Age Range
             * @default []
             */
            best_age_range: string[];
            /** Cost Tier */
            cost_tier?: string | null;
            /** Indoor Outdoor */
            indoor_outdoor?: string | null;
            /** Weather Sensitivity */
            weather_sensitivity?: string | null;
            /** Time Status */
            time_status: string;
        };
        /** EventsResponse */
        EventsResponse: {
            /** Events */
            events: components["schemas"]["Event"][];
            /** Count */
            count: number;
            /** Filters Applied */
            filters_applied: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_events_events_get: {
        parameters: {
            query?: {
                /** @description now | soon | weekend (omit for all) */
                time_filter?: string | null;
                /** @description Child's age in years (e.g. 2.5) */
                child_age?: number | null;
                /** @description Current weather is rainy */
                is_raining?: boolean;
                /** @description User latitude */
                lat?: number | null;
                /** @description User longitude */
                lng?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
